name: CI

on:
  push:
    branches: 
      - main
      - lavanya
      - tanishqa
      - Ruchitha
  pull_request:
    branches: 
      - main
      - lavanya
      - tanishqa
      - Ruchitha

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.8, 3.9]  # You can specify multiple Python versions if needed

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies on Ubuntu
      if: runner.os == 'Linux'
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install dependencies on Windows
      if: runner.os == 'Windows'
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install dependencies on macOS
      if: runner.os == 'macOS'
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: pytest

    - name: Check code formatting with black
      run: |
        pip install black
        black --check .
