name: CI

on:
  push:
    branches: 
      - main
      - lavanya
      - tanishqa
      - Ruchitha
  pull_request:
    branches: 
      - main
      - lavanya
      - tanishqa
      - Ruchitha

jobs:
  test:
    runs-on: windows-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.9  # Specify your desired Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirement.txt  # Using the correct file name

    - name: Run tests
      run: pytest

    - name: Install Black
      run: pip install black

    - name: Check code formatting with Black
      run: |
        black --check .  # Check if code is formatted according to Black
      continue-on-error: true  # Continue even if Black finds formatting issues

    - name: Report Black formatting issues
      if: failure()  # This step will run if the previous step failed
      run: |
        echo "Code formatting issues found. Please run 'black .' locally to format your code."
